services:
  superchat_db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - superchat_postgres_data:/var/lib/postgresql/data
  pgadmin_superchat:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 15432:80
    depends_on:
      - superchat_db
    volumes:
      - supercht_pgadmin_data:/var/lib/pgadmin
    
volumes:
  superchat_postgres_data:
  supercht_pgadmin_data: